MvcTasks.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcTasks.DomainModel.Abstract;

namespace MvcTasks.WebUI.Controllers
{
    public class NavController : Controller
    {
        private ITasksRepository _repository;

        public NavController(ITasksRepository repo)
        {
            _repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = _repository.Tasks
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);

            return PartialView(categories);
        } 
    }
}

MvcTasks.WebUI/Views/Shared/TaskSummary.cshtml
@model MvcTasks.DomainModel.Entities.Task

@{
    AjaxOptions ajaxOpts = new AjaxOptions 
    {
        UpdateTargetId = "item",
        Url = Url.Action("DetailedTask")
    };
}

<script type="text/javascript">
$(".item").click(function(){ 
    window.location=$(this).find("a").attr("href"); 
    return false; 
}); 
</script>

<div class="item">
    @*<h3>@Model.Name</h3>
    @Model.Description
    <h4>@Model.TaskStatus.Description</h4>*@
    <a href="@Url.Action("DetailedTask", "Home", new {taskID = @Model.TaskID })"><h2>@Model.Name</h2></a> 
</div>

MvcTasks.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>@ViewBag.Title</title>
  <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
  <link href="~/Content/themes/base/jquery-ui.css" type="text/css" rel="stylesheet" />
  @*@Scripts.Render("~/bundles/jquery")*@
  <script src="~/Scripts/jquery-1.7.1.js" type="text/javascript"></script>
  <script src="~/Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
  <script src="~/Scripts/jquery-ui-1.8.20.js" type="text/javascript"></script>
  <script src="~/Scripts/jquery-ui-1.8.20.min.js" type="text/javascript"></script>
  <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
  @*@Scripts.Render("~/bundles/modernizr")*@

  <script type="text/javascript">
      $(function () {

          $('.modal-class').click(function () {
              $("#modal-popup").load(this.href, function () {
                  var target = document.getElementsByClassName("modal-popup")
                  $(target).dialog({
                      autoOpen: true,
                      closeOnEscape: true,
                      width: 400,
                      resizable: false,
                      title: 'Login Form',
                      modal: true,
                      buttons: {
                          Login: function() {
                          // perform login
                    $.post("@Url.Action("Login", "User")",
                    {
                        username: $('#Email').val(),
                        password: $('#Password').val()
                    },
                    function() {
                            $('.modal-popup').dialog("close");
                            $('#main').load("@Url.Action("Index", "User")",
                            {
                                uniqueName: $('#Email').val()
                            });
                    });
                },
                          Cancel: function () {
                              $(this).dialog("close");
                          }
                      }
                  });
              })
              return false;
          });
      });
</script>

</head>
<div id="main">
<div id="modal-popup"></div>

    <div class="header">
    <h1>TASKS</h1>
        @if (Request.IsAuthenticated)
        {
            <strong>@Html.Encode(User.Identity.Name)</strong>
            @Html.ActionLink("Log Out", "Logout", "User")
            <span> | </span>
            @Html.ActionLink("Profile", "Index", "User", new { uniqueName = User.Identity.Name }, new object { })
        }
        else
        {
            @Html.ActionLink("Register", "Register", "User")
            <span> | </span>
            @Html.ActionLink("Log In", "Login", "User", null, new { id = "login-popup", @class="modal-class" })
        }
    </div>
    <div class="categories">
        @{Html.RenderAction("Menu", "Nav");}
    </div>
    <div class="footer">
    </div>
  <div class="content">
		@RenderBody()
  </div> 
  <div id="right_section">
 
    </div>
</div>
  <footer>
    <h1>THIS IS THE FOOTER</h1>
  </footer> 


</html>